import type { SportsResult } from '@/core/types';
import { author } from './users';

/* ============================================================================
   365 · RESULTADOS DE EJEMPLO
   ----------------------------------------------------------------------------
   Cinco disciplinas (fútbol, básquetbol, tenis, vóleibol y atletismo) por tres
   categorías (infantil, intermedia y superior).

   En atletismo no hay marcador: `scoreFor` y `scoreAgainst` van en `null` y el
   resultado se registra como participación, con las posiciones en `highlights`.
   ========================================================================== */

const daysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString();

export const seedSportsResults: SportsResult[] = [
  {
    id: 'res_1',
    discipline: 'futbol',
    level: 'superior',
    playedAt: daysAgo(2),
    opponent: 'Liceo San Andrés',
    competition: 'Torneo interescolar · fecha 5',
    location: 'Cancha principal',
    scoreFor: 3,
    scoreAgainst: 1,
    outcome: 'victoria',
    highlights:
      'Goles de Matías Fuentes (2) y Diego Herrera. El equipo queda segundo en la tabla, a dos puntos del líder.',
    author: author('usr_admin'),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'res_2',
    discipline: 'futbol',
    level: 'intermedia',
    playedAt: daysAgo(2),
    opponent: 'Colegio Los Robles',
    competition: 'Torneo interescolar · fecha 5',
    location: 'Cancha principal',
    scoreFor: 1,
    scoreAgainst: 1,
    outcome: 'empate',
    highlights: 'Empate en el último minuto tras un partido muy disputado en el segundo tiempo.',
    author: author('usr_admin'),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'res_3',
    discipline: 'futbol',
    level: 'infantil',
    playedAt: daysAgo(9),
    opponent: 'Escuela Santa Elena',
    competition: 'Copa formativa',
    location: 'Cancha visitante',
    scoreFor: 0,
    scoreAgainst: 2,
    outcome: 'derrota',
    highlights:
      'Buen rendimiento defensivo en el primer tiempo. La categoría cierra su primera fase.',
    author: author('usr_admin'),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 'res_4',
    discipline: 'basquetbol',
    level: 'superior',
    playedAt: daysAgo(4),
    opponent: 'Instituto del Valle',
    competition: 'Liga escolar · semifinal',
    location: 'Gimnasio techado',
    scoreFor: 58,
    scoreAgainst: 52,
    outcome: 'victoria',
    highlights: 'Clasificación a la final. Máxima anotadora: Antonia Salas con 21 puntos.',
    author: author('usr_admin'),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: 'res_5',
    discipline: 'basquetbol',
    level: 'intermedia',
    playedAt: daysAgo(11),
    opponent: 'Colegio Los Robles',
    competition: 'Liga escolar · fecha 4',
    location: 'Gimnasio techado',
    scoreFor: 41,
    scoreAgainst: 47,
    outcome: 'derrota',
    highlights:
      'Partido cerrado hasta el último cuarto. La categoría sigue en carrera por el repechaje.',
    author: author('usr_admin'),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: 'res_6',
    discipline: 'voleibol',
    level: 'superior',
    playedAt: daysAgo(6),
    opponent: 'Liceo San Andrés',
    competition: 'Torneo interescolar · cuartos de final',
    location: 'Gimnasio techado',
    scoreFor: 3,
    scoreAgainst: 0,
    outcome: 'victoria',
    highlights:
      'Sets 25-19, 25-21 y 25-17. Avanza a semifinales sin ceder un set en toda la ronda.',
    author: author('usr_admin'),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: 'res_7',
    discipline: 'voleibol',
    level: 'infantil',
    playedAt: daysAgo(13),
    opponent: 'Escuela Santa Elena',
    competition: 'Encuentro formativo',
    location: 'Gimnasio techado',
    scoreFor: 2,
    scoreAgainst: 1,
    outcome: 'victoria',
    highlights: 'Primera victoria de la categoría en el año. Se destaca el trabajo en recepción.',
    author: author('usr_admin'),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    id: 'res_8',
    discipline: 'tenis',
    level: 'superior',
    playedAt: daysAgo(8),
    opponent: 'Instituto del Valle',
    competition: 'Circuito escolar · segunda ronda',
    location: 'Club de tenis municipal',
    scoreFor: 2,
    scoreAgainst: 1,
    outcome: 'victoria',
    highlights: 'Dos singles ganados y un dobles perdido. Se avanza a la tercera ronda.',
    author: author('usr_admin'),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: 'res_9',
    discipline: 'tenis',
    level: 'intermedia',
    playedAt: daysAgo(15),
    opponent: 'Colegio Los Robles',
    competition: 'Circuito escolar · primera ronda',
    location: 'Club de tenis municipal',
    scoreFor: 1,
    scoreAgainst: 2,
    outcome: 'derrota',
    highlights:
      'Serie definida en el dobles decisivo. La categoría cierra su participación del semestre.',
    author: author('usr_admin'),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    id: 'res_10',
    discipline: 'atletismo',
    level: 'superior',
    playedAt: daysAgo(5),
    opponent: 'Encuentro regional de pista',
    competition: 'Campeonato regional escolar',
    location: 'Estadio municipal',
    scoreFor: null,
    scoreAgainst: null,
    outcome: 'participacion',
    highlights:
      'Primer lugar en 400 m planos, segundo lugar en salto largo y cuarto lugar en la posta 4x100. Dos marcas personales en la jornada.',
    author: author('usr_admin'),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'res_11',
    discipline: 'atletismo',
    level: 'intermedia',
    playedAt: daysAgo(5),
    opponent: 'Encuentro regional de pista',
    competition: 'Campeonato regional escolar',
    location: 'Estadio municipal',
    scoreFor: null,
    scoreAgainst: null,
    outcome: 'participacion',
    highlights: 'Tercer lugar en 800 m planos y quinto lugar en lanzamiento de la bala.',
    author: author('usr_admin'),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'res_12',
    discipline: 'atletismo',
    level: 'infantil',
    playedAt: daysAgo(19),
    opponent: 'Encuentro comunal formativo',
    competition: 'Encuentro comunal',
    location: 'Pista del complejo deportivo',
    scoreFor: null,
    scoreAgainst: null,
    outcome: 'participacion',
    highlights: 'Participación de 14 estudiantes. Segundo lugar por equipos en la posta mixta.',
    author: author('usr_admin'),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
];
